services:
  marzban:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file: .env
    volumes:
      - /var/lib/marzban:/var/lib/marzban
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - marzban